name: Tests

on: [push]

jobs:
  capabilitiesToResources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Install packages
        run: npm i
      - name: Run
        run: npm run capabilitiesToResources