name: Tests

on: [push]

jobs:
  capabilitiesToResources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/labeler@v2
        with:
          repo-token: "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"
      - name: Install packages
        run: npm i
      - name: Run
        env:
          GITHUB_TOKEN: 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
        run: npm run capabilitiesToResources