name: build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{secrets.GH_TOKEN}}
    steps:
    - uses: actions/checkout@v2
    - name: Move release to draft
      run: |
        gh release edit $release --draft=true
      env:
        TAG_NAME: ${{ github.event.tagName }}
    - name: Run npm install, build and test
      run: |
        npm i
        npm run build --if-present
        npm run lint --if-present
        npm test --if-present
    - run: zip -r lib.zip lib
    - name: Upload production artifacts
      run: |
        gh release upload $TAG_NAME "lib.zip#build"
        gh release edit $TAG_NAME --draft=false
      env:
        TAG_NAME: ${{ github.event.tagName }}
